name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Kích hoạt khi có thay đổi trên nhánh main
  workflow_dispatch: # Cho phép chạy thủ công

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Kiểm tra mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập JDK cho Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build Spring Boot với Maven (hoặc Gradle)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Đăng nhập vào DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest .

      # 6. Push Docker Image lên DockerHub
      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest
